services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"   # Jenkins Web UI
      - "50000:50000" # JNLP agent port
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
      - JENKINS_OPTS=--argumentsRealm.passwd.admin=admin --argumentsRealm.roles.user=admin
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml # 自动加载 JCasC 配置
    volumes:
      - ./jenkins_home:/var/jenkins_home   # Jenkins数据持久化
      - ./:/var/jenkins_home/workspace/pipeline # 挂载当前项目到 Jenkins workspace，便于测试 shared library
      - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml # 挂载 JCasC 配置
    # 可选：加速插件下载
    # extra_hosts:
    #   - "updates.jenkins.io:114.114.114.114"

# 使用方法：
# 1. mkdir jenkins_home
# 2. docker-compose up -d
# 3. 访问 http://localhost:8080
# 4. 初始密码在 ./jenkins_home/secrets/initialAdminPassword
# 5. Jenkins 会自动注册 shared library，无需手动配置